import { Boxes, CalendarClock, Download, FileSpreadsheet, FileText, PackageMinus, Truck } from "lucide-react";
import { useState } from "react";
import { ReportAPI } from "../api/endpoints";
import { useData } from "../context/DataContext";
import { expiryStatus, stockStatus } from "../utils/format";

const REPORTS = [
  { key: "inventory", title: "Inventory summary", desc: "Full medicine list with stock levels and value.", icon: Boxes },
  { key: "expiry", title: "Expiry report", desc: "Batches expiring within 45 days, with days remaining.", icon: CalendarClock },
  { key: "lowstock", title: "Low-stock report", desc: "Medicines at or below their reorder level.", icon: PackageMinus },
  { key: "supplier", title: "Supplier performance", desc: "On-time delivery rate and order history by supplier.", icon: Truck },
];

export default function Reports() {
  const { medicines, suppliers } = useData();
  const [exporting, setExporting] = useState("");

  const download = async (key, format) => {
    if (format === "pdf") return downloadPdf(key);
    if (key === "inventory") return downloadInventoryCsv();
    const rows = buildRows(key, medicines, suppliers);
    const content = toCsv(rows);
    const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medistock-${key}-report.${format === "excel" ? "csv" : "csv"}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadInventoryCsv = async () => {
    setExporting("inventory");
    try {
      const response = await ReportAPI.exportInventoryCsv();
      const url = URL.createObjectURL(new Blob([response.data], { type: "text/csv;charset=utf-8;" }));
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = "medistock_inventory.csv";
      anchor.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting("");
    }
  };

  const downloadPdf = async (key) => {
    setExporting(key);
    try {
      const response = await ReportAPI.exportPdf(key);
      const url = URL.createObjectURL(new Blob([response.data], { type: "application/pdf" }));
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = `medistock-${key}-report.pdf`;
      anchor.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting("");
    }
  };

  return (
    <div className="space-y-4">
      <div>
        <h2 className="font-display text-base font-semibold text-ink">Reports &amp; data export</h2>
        <p className="text-sm text-muted">
          Generate a report from current inventory data. PDF exports are generated by the Spring Boot report service.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        {REPORTS.map((r) => (
          <div key={r.key} className="rounded-lg border border-line bg-surface p-4 shadow-card">
            <span className="grid h-9 w-9 place-items-center rounded bg-primary-light text-primary">
              <r.icon size={17} />
            </span>
            <h3 className="mt-3 font-display text-sm font-semibold text-ink">{r.title}</h3>
            <p className="mt-1 text-xs text-muted">{r.desc}</p>
            <div className="mt-4 flex gap-2">
              <button
                onClick={() => download(r.key, "excel")}
                disabled={exporting === r.key}
                className="focus-ring flex items-center gap-1.5 rounded border border-line px-3 py-1.5 text-xs font-medium text-ink hover:bg-bg"
              >
                <FileSpreadsheet size={13} /> Excel (.csv)
              </button>
              <button
                onClick={() => download(r.key, "pdf")}
                disabled={exporting === r.key}
                className="focus-ring flex items-center gap-1.5 rounded border border-line px-3 py-1.5 text-xs font-medium text-ink hover:bg-bg"
              >
                <FileText size={13} /> {exporting === r.key ? "Preparing..." : "PDF"}
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="flex items-center gap-2 rounded-lg border border-dashed border-line bg-surface px-4 py-3 text-xs text-muted">
        <Download size={14} />
        Inventory CSV exports are generated server-side from the complete database. Other CSV reports use the loaded live data, while PDFs are generated by Spring Boot.
      </div>
    </div>
  );
}

function buildRows(key, medicines, suppliers) {
  const supplierName = (id) => suppliers.find((s) => s.id === id)?.name || id;

  if (key === "inventory") {
    return [
      ["ID", "Name", "Batch", "Category", "Supplier", "Quantity", "Price"],
      ...medicines.map((m) => [m.id, m.name, m.batchNumber, m.category, supplierName(m.supplierId), m.quantity, m.price]),
    ];
  }
  if (key === "expiry") {
    return [
      ["ID", "Name", "Batch", "Expiry date", "Days remaining", "Status"],
      ...medicines.map((m) => {
        const s = expiryStatus(m.expiryDate);
        return [m.id, m.name, m.batchNumber, m.expiryDate, s.days, s.key];
      }),
    ];
  }
  if (key === "lowstock") {
    return [
      ["ID", "Name", "Quantity", "Reorder level", "Status"],
      ...medicines
        .filter((m) => stockStatus(m.quantity, m.reorderLevel).key !== "ok")
        .map((m) => [m.id, m.name, m.quantity, m.reorderLevel, stockStatus(m.quantity, m.reorderLevel).label]),
    ];
  }
  return [
    ["ID", "Name", "Contact", "Email", "On-time rate", "Last order"],
    ...suppliers.map((s) => [s.id, s.name, s.contact, s.email, `${s.performance}%`, s.lastOrder]),
  ];
}

function toCsv(rows) {
  return rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n");
}
